achievements = [
    'Frugal',
    'Stingy',
    # 'Miserly',
    # 'Greedy',
    'Zone Explorer',
    'Zone Warrior',
    'Zone Master',
    # 'Zone Lord',
    # 'Zone King',
    # 'Zone God',
    # 'Zone Owner',
    # 'Zone Pwn',
    # 'Zoner',
    # 'Zone Pro',
    # 'Zone Crusher',
    # 'Zone Connoisseur',
    # 'Bounty: The Green One',
    # 'Bounty: Woodchip, the Rodent',
    # 'Bounty: Queen of Bloops',
    # 'Bounty: Doppler the Robot',
    # 'Bounty: Rashon the Duke',
    # 'Bounty: The Dark Wizard',
    # 'Bounty: Tako, Head of the Octopi',
    # 'Bounty: Tako Returns',
    # 'Bounty: Lagomorph of the Caerbannog',
    'Lethal',
    'Ruinous',
    'Calamitous',
    # 'Cataclysmic',
    # 'A lot of Damage',
    # 'Too Stronk',
    # 'You lift?',
    # 'Leg days skipped: 0',
    # 'Unreal Power',
    # 'Worlds Strongest',
    'Frenzied',
    'Convulsions',
    'Deadly',
    'Assassin',
    'Boss Slaughter',
    # 'Boss Massacre',
    # 'Boss Exterminator',
    # 'Boss Murderer',
    # 'Boss Genocide',
    'Proficient Clicking',
    'Sore Finger',
    'Carpal Tunnel',
    'Broken Mouse',
    # 'Finger Amputee',
    'Uptown',
    'Fat Cat',
    'Loaded',
    'The 1%',
    # 'The 0.01%',
    # 'Buffett',
    # 'Gates',
    # 'Rockefeller',
    # 'Money Aint a Thang',
    # 'Money Tree',
    # 'Gold Hoarder',
    # 'Super Rich',
    # 'Filthy Rich',
    'Guide',
    'Coach',
    # 'Teacher',
    # 'Mentor',
    # 'Levelupper',
    # 'Super Levelupper',
    'Killer',
    'Butcher',
    # 'Executioner',
    # 'Monster Genocide',
    # 'Terminator',
    # 'Mass Murderer',
    'Considerate',
    'Generous',
    # 'Benevolent',
    # 'Magnanimous',
    # 'Treasure Hunter'
]